module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "©𝐌r DEVIL  💚",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "923187379684",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "true",
  "ANTI_CALL": "false",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "923187379684",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 DEVIL 💚",
  "OWNER_NUMBER": "923187379684",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
};
